#! /usr/bin/env python
import os 
bld.shlib(
	source = 'c/daoTools.c',
	includes = '../include '+os.getenv('DAOROOT')+'/include/',
	linkflags = ['-L'+os.getenv('DAOROOT')+'/lib/','-L'+os.getenv('DAOROOT')+'/lib64/'],
	#cflags = ['-Ofast', '-Wall', '-Wextra', '-Werror', '-pipe', '-fdiagnostics-color=auto'],
	cflags = ['-Ofast', '-Wall', '-Wextra', '-pipe', '-fdiagnostics-color=auto'],
	ldflags = ['-ldao', '-lpthread', '-lrt', '-lm'],
	target = 'daoTools',
	name   = 'daoTools',
	vnum   = '0.0.1')


