#! /usr/bin/env python
import os 
import platform
if platform.system() == "Darwin":
    my_ld_flags = ['']
    my_link_flags = ['-L'+os.getenv('DAOROOT')+'/lib/']
    # Homebrew's fftw isn't on the default linker search path (it lives
    # under a Cellar prefix), so pass through the -L path pkg-config found
    # at configure time or -lfftw3f/-lfftw3 below fail with "library not found".
    if bld.env.FFTW_AVAILABLE:
        my_link_flags += ['-L' + p for p in bld.env.LIBPATH_FFTW3F + bld.env.LIBPATH_FFTW3]
    my_cxx_flags = ['-std=c++14']
    my_cflags = ['-O3', '-ffast-math']
else:
    my_ld_flags = ['-lrt']
    my_link_flags = ['-L'+os.getenv('DAOROOT')+'/lib/','-L'+os.getenv('DAOROOT')+'/lib64/']
    my_cxx_flags = ['']
    # -march=native: this lib is built and run on the same host (AVX2 + FMA on
    # the EPYC). -Ofast keeps -ffast-math; FTZ/DAZ is set at runtime by
    # daoToolsEnableFTZ() so we do not rely on crtfastmath being linked.
    my_cflags = ['-Ofast', '-march=native', '-funroll-loops']
    my_defines = []

daoTools_sources = ['c/daoTools.c']
daoTools_ldflags = ['-ldao', '-lpthread', '-lm'] + my_ld_flags

# FFT-based correlation centroider (daoToolsCorrFFT): only built when both
# fftw3f and fftw3 were found at configure time (see wscript configure()).
if bld.env.FFTW_AVAILABLE:
	daoTools_sources += ['c/daoToolsCorrFFT.c']
	daoTools_ldflags += ['-lfftw3f', '-lfftw3']

bld.shlib(
	source = daoTools_sources,
	includes = '../include '+os.getenv('DAOROOT')+'/include/',
	linkflags = my_link_flags,
	#cflags = ['-Ofast', '-Wall', '-Wextra', '-Werror', '-pipe', '-fdiagnostics-color=auto'],
	cflags = my_cflags + ['-Wall', '-Wextra', '-pipe', '-fdiagnostics-color=auto', '-fstack-protector'],
	ldflags = daoTools_ldflags,
	target = 'daoTools',
	name   = 'daoTools',
	vnum   = '0.0.1')


