name: Clone Test

on:
  push:
    branches: [ CI-Workflow ]
  pull_request:
    branches: [ CI-Workflow ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout daoBase
        uses: actions/checkout@v4
        with:
          repository: Durham-Adaptive-Optics/daoBase
          path: daoBase
          token: ${{ secrets.CI_CLONE_ACCESS_TOKEN }}

